# Generated by Django 4.2.1 on 2023-06-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='url',
        ),
    ]
